// <auto-generated />
namespace KazNTU.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_image_column_title : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_image_column_title));
        
        string IMigrationMetadata.Id
        {
            get { return "201803281115313_change_image_column_title"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
